// This file has been generated by Specta. DO NOT EDIT.

export type AccessRule = { allow?: string[] | null; deny?: string[] | null }

export type AddProgress = { entry: ProgressEntry; summary?: string | null }

export type AgentSpawnRecord = { toolUseId: string; subagentType: string; model?: string | null; background: boolean; at: number }

export type AgentState = { id: string; type: string; status: string; description: string; parentId?: string | null; spawnedBy?: string | null; name?: string | null }

export type Assignment = { runtime: Runtime; model: string; effort: Effort; role?: string | null }

export type Board = { cards: Card[]; focus?: string | null; policies?: { [key in string]: Policy } | null }

export type Card = { id: string; title: string; objective: string; requirements: string[]; status: Status; phase?: string | null; assignment: Assignment; summary: string; entries: ProgressEntry[]; updatedAt: string }

export type Correlation = { cardId?: string | null; sessionId: string; promptId?: string | null; at: number }

export type CreateCard = { id: string; title: string; objective: string; requirements: string[]; status: Status; phase?: string | null; assignment: Assignment; summary: string }

export type Effort = string | number

export type PatchBoard = { focus?: string | null; policies?: { [key in string]: Policy } | null }

export type PatchCard = { title?: string | null; objective?: string | null; requirements?: string[] | null; status?: Status | null; phase?: string | null; assignment?: Assignment | null; summary?: string | null }

export type Policy = { skills?: AccessRule | null; agents?: AccessRule | null }

export type ProgressEntry = { at: string; by: string; note: string }

export type Runtime = "claude" | "codex"

export type SkillUse = { skill: string; at: number; via: SkillVia }

export type SkillVia = "tool" | "expansion" | "blocked"

export type Status = "backlog" | "ready" | "doing" | "review" | "done" | "blocked"

export type TokenUsage = { input: number; output: number; cacheRead: number; cacheCreation: number }

export type ToolUse = { tool: string; at: number }

export type TurnRecord = { cardId?: string | null; sessionId?: string | null; promptId?: string | null; turnId: string; agentId?: string | null; reason: string; durationMs: number; model?: string | null; effort?: Effort | null; tokens?: TokenUsage | null; answer?: string | null; answerLength?: number | null; tools: ToolUse[]; skills: SkillUse[]; agents: AgentSpawnRecord[]; agentStates: AgentState[]; at: number }
